# # config/packages/vich_uploader.yaml or app/config/config.yml
# vich_uploader:
#     db_driver: orm

#     metadata:
#         type: attribute

#     mappings:
#         products:
#             uri_prefix: /images/user
#             upload_destination: "%kernel.project_dir%/public/uploads/images"
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
